resource "pingone_davinci_connector_instance" "connectorSecuronix" {
  environment_id = var.pingone_environment_id

  connector = {
    id = "connectorSecuronix"
  }
  name = "My awesome connectorSecuronix"
  properties = jsonencode({
    "allowChildCases" = var.connectorsecuronix_property_allow_child_cases
    "city" = var.connectorsecuronix_property_city
    "companycode" = var.connectorsecuronix_property_companycode
    "costcentername" = var.connectorsecuronix_property_costcentername
    "country" = var.connectorsecuronix_property_country
    "countrycode" = var.connectorsecuronix_property_countrycode
    "department" = var.connectorsecuronix_property_department
    "division" = var.connectorsecuronix_property_division
    "domainName" = var.connectorsecuronix_property_domain_name
    "employeeId" = var.connectorsecuronix_property_employee_id
    "employeetype" = var.connectorsecuronix_property_employeetype
    "employeetypedescription" = var.connectorsecuronix_property_employeetypedescription
    "eventTimeFrom" = var.connectorsecuronix_property_event_time_from
    "eventTimeTo" = var.connectorsecuronix_property_event_time_to
    "firstname" = var.connectorsecuronix_property_firstname
    "from" = var.connectorsecuronix_property_from
    "hiredate" = var.connectorsecuronix_property_hiredate
    "incidentId" = var.connectorsecuronix_property_incident_id
    "ipfrom" = var.connectorsecuronix_property_ipfrom
    "ipto" = var.connectorsecuronix_property_ipto
    "jobcode" = var.connectorsecuronix_property_jobcode
    "key" = var.connectorsecuronix_property_key
    "lanid" = var.connectorsecuronix_property_lanid
    "lastname" = var.connectorsecuronix_property_lastname
    "latitude" = var.connectorsecuronix_property_latitude
    "location" = var.connectorsecuronix_property_location
    "longitude" = var.connectorsecuronix_property_longitude
    "lookupname" = var.connectorsecuronix_property_lookupname
    "manageremployeeid" = var.connectorsecuronix_property_manageremployeeid
    "max" = var.connectorsecuronix_property_max
    "offset" = var.connectorsecuronix_property_offset
    "prettyJson" = var.connectorsecuronix_property_pretty_json
    "queryId" = var.connectorsecuronix_property_query_id
    "rangeType" = var.connectorsecuronix_property_range_type
    "region" = var.connectorsecuronix_property_region
    "sort" = var.connectorsecuronix_property_sort
    "source" = var.connectorsecuronix_property_source
    "status" = var.connectorsecuronix_property_status
    "statusdescription" = var.connectorsecuronix_property_statusdescription
    "timeZone" = var.connectorsecuronix_property_time_zone
    "title" = var.connectorsecuronix_property_title
    "to" = var.connectorsecuronix_property_to
    "token" = var.connectorsecuronix_property_token
    "tpiAddress" = var.connectorsecuronix_property_tpi_address
    "tpiCategory" = var.connectorsecuronix_property_tpi_category
    "tpiCriticality" = var.connectorsecuronix_property_tpi_criticality
    "tpiDate" = var.connectorsecuronix_property_tpi_date
    "tpiDomain" = var.connectorsecuronix_property_tpi_domain
    "tpiSrc" = var.connectorsecuronix_property_tpi_src
    "tpiType" = var.connectorsecuronix_property_tpi_type
    "userid" = var.connectorsecuronix_property_userid
    "valueUCustomfield11" = var.connectorsecuronix_property_value_ucustomfield11
    "valueUCustomfield4" = var.connectorsecuronix_property_value_ucustomfield4
    "violator" = var.connectorsecuronix_property_violator
    "workemail" = var.connectorsecuronix_property_workemail
    "workphone" = var.connectorsecuronix_property_workphone
  })
}
