resource "pingone_davinci_connector_instance" "connector-oai-hubspotcompanies" {
  environment_id = var.pingone_environment_id

  connector = {
    id = "connector-oai-hubspotcompanies"
  }
  name = "My awesome connector-oai-hubspotcompanies"
  properties = jsonencode({
    "authBearerToken" = var.connector-oai-hubspotcompanies_property_auth_bearer_token
    "basePath" = var.connector-oai-hubspotcompanies_property_base_path
    "deleteCrmV3ObjectsCompaniesCompanyIdArchive_company_id" = var.connector-oai-hubspotcompanies_property_delete_crm_v3_objects_companies_company_id_archive_company_id
    "deleteCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeToObjectIdArchive_company_id" = var.connector-oai-hubspotcompanies_property_delete_crm_v4_objects_companies_company_id_associations_to_object_type_to_object_id_archive_company_id
    "deleteCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeToObjectIdArchive_to_object_id" = var.connector-oai-hubspotcompanies_property_delete_crm_v4_objects_companies_company_id_associations_to_object_type_to_object_id_archive_to_object_id
    "deleteCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeToObjectIdArchive_to_object_type" = var.connector-oai-hubspotcompanies_property_delete_crm_v4_objects_companies_company_id_associations_to_object_type_to_object_id_archive_to_object_type
    "getCrmV3ObjectsCompaniesCompanyIdGetById_archived" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_company_id_get_by_id_archived
    "getCrmV3ObjectsCompaniesCompanyIdGetById_associations" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_company_id_get_by_id_associations
    "getCrmV3ObjectsCompaniesCompanyIdGetById_company_id" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_company_id_get_by_id_company_id
    "getCrmV3ObjectsCompaniesCompanyIdGetById_id_property" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_company_id_get_by_id_id_property
    "getCrmV3ObjectsCompaniesCompanyIdGetById_properties" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_company_id_get_by_id_properties
    "getCrmV3ObjectsCompaniesCompanyIdGetById_properties_with_history" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_company_id_get_by_id_properties_with_history
    "getCrmV3ObjectsCompaniesGetPage_after" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_get_page_after
    "getCrmV3ObjectsCompaniesGetPage_archived" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_get_page_archived
    "getCrmV3ObjectsCompaniesGetPage_associations" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_get_page_associations
    "getCrmV3ObjectsCompaniesGetPage_limit" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_get_page_limit
    "getCrmV3ObjectsCompaniesGetPage_properties" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_get_page_properties
    "getCrmV3ObjectsCompaniesGetPage_properties_with_history" = var.connector-oai-hubspotcompanies_property_get_crm_v3_objects_companies_get_page_properties_with_history
    "getCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeGetAll_after" = var.connector-oai-hubspotcompanies_property_get_crm_v4_objects_companies_company_id_associations_to_object_type_get_all_after
    "getCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeGetAll_company_id" = var.connector-oai-hubspotcompanies_property_get_crm_v4_objects_companies_company_id_associations_to_object_type_get_all_company_id
    "getCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeGetAll_limit" = var.connector-oai-hubspotcompanies_property_get_crm_v4_objects_companies_company_id_associations_to_object_type_get_all_limit
    "getCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeGetAll_to_object_type" = var.connector-oai-hubspotcompanies_property_get_crm_v4_objects_companies_company_id_associations_to_object_type_get_all_to_object_type
    "patchCrmV3ObjectsCompaniesCompanyIdUpdate_company_id" = var.connector-oai-hubspotcompanies_property_patch_crm_v3_objects_companies_company_id_update_company_id
    "patchCrmV3ObjectsCompaniesCompanyIdUpdate_id_property" = var.connector-oai-hubspotcompanies_property_patch_crm_v3_objects_companies_company_id_update_id_property
    "patchCrmV3ObjectsCompaniesCompanyIdUpdate_simplePublicObjectInput_SimplePublicObjectInput_properties" = var.connector-oai-hubspotcompanies_property_patch_crm_v3_objects_companies_company_id_update_simple_public_object_input__simple_public_object_input_properties
    "postCrmV3ObjectsCompaniesBatchArchiveArchive_batchInputSimplePublicObjectId_BatchInputSimplePublicObjectId_inputs" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_batch_archive_archive_batch_input_simple_public_object_id__batch_input_simple_public_object_id_inputs
    "postCrmV3ObjectsCompaniesBatchCreateCreate_batchInputSimplePublicObjectInput_BatchInputSimplePublicObjectInput_inputs" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_batch_create_create_batch_input_simple_public_object_input__batch_input_simple_public_object_input_inputs
    "postCrmV3ObjectsCompaniesBatchReadRead_archived" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_batch_read_read_archived
    "postCrmV3ObjectsCompaniesBatchReadRead_batchReadInputSimplePublicObjectId_BatchReadInputSimplePublicObjectId_idProperty" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_batch_read_read_batch_read_input_simple_public_object_id__batch_read_input_simple_public_object_id_id_property
    "postCrmV3ObjectsCompaniesBatchReadRead_batchReadInputSimplePublicObjectId_BatchReadInputSimplePublicObjectId_inputs" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_batch_read_read_batch_read_input_simple_public_object_id__batch_read_input_simple_public_object_id_inputs
    "postCrmV3ObjectsCompaniesBatchReadRead_batchReadInputSimplePublicObjectId_BatchReadInputSimplePublicObjectId_properties" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_batch_read_read_batch_read_input_simple_public_object_id__batch_read_input_simple_public_object_id_properties
    "postCrmV3ObjectsCompaniesBatchReadRead_batchReadInputSimplePublicObjectId_BatchReadInputSimplePublicObjectId_propertiesWithHistory" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_batch_read_read_batch_read_input_simple_public_object_id__batch_read_input_simple_public_object_id_properties_with_history
    "postCrmV3ObjectsCompaniesBatchUpdateUpdate_batchInputSimplePublicObjectBatchInput_BatchInputSimplePublicObjectBatchInput_inputs" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_batch_update_update_batch_input_simple_public_object_batch_input__batch_input_simple_public_object_batch_input_inputs
    "postCrmV3ObjectsCompaniesCreate_simplePublicObjectInput_SimplePublicObjectInput_properties" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_create_simple_public_object_input__simple_public_object_input_properties
    "postCrmV3ObjectsCompaniesMergeMerge_publicMergeInput_PublicMergeInput_objectIdToMerge" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_merge_merge_public_merge_input__public_merge_input_object_id_to_merge
    "postCrmV3ObjectsCompaniesMergeMerge_publicMergeInput_PublicMergeInput_primaryObjectId" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_merge_merge_public_merge_input__public_merge_input_primary_object_id
    "postCrmV3ObjectsCompaniesSearchDoSearch_publicObjectSearchRequest_PublicObjectSearchRequest_after" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_search_do_search_public_object_search_request__public_object_search_request_after
    "postCrmV3ObjectsCompaniesSearchDoSearch_publicObjectSearchRequest_PublicObjectSearchRequest_filterGroups" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_search_do_search_public_object_search_request__public_object_search_request_filter_groups
    "postCrmV3ObjectsCompaniesSearchDoSearch_publicObjectSearchRequest_PublicObjectSearchRequest_limit" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_search_do_search_public_object_search_request__public_object_search_request_limit
    "postCrmV3ObjectsCompaniesSearchDoSearch_publicObjectSearchRequest_PublicObjectSearchRequest_properties" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_search_do_search_public_object_search_request__public_object_search_request_properties
    "postCrmV3ObjectsCompaniesSearchDoSearch_publicObjectSearchRequest_PublicObjectSearchRequest_query" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_search_do_search_public_object_search_request__public_object_search_request_query
    "postCrmV3ObjectsCompaniesSearchDoSearch_publicObjectSearchRequest_PublicObjectSearchRequest_sorts" = var.connector-oai-hubspotcompanies_property_post_crm_v3_objects_companies_search_do_search_public_object_search_request__public_object_search_request_sorts
    "putCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeToObjectIdCreate_association_spec" = var.connector-oai-hubspotcompanies_property_put_crm_v4_objects_companies_company_id_associations_to_object_type_to_object_id_create_association_spec
    "putCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeToObjectIdCreate_company_id" = var.connector-oai-hubspotcompanies_property_put_crm_v4_objects_companies_company_id_associations_to_object_type_to_object_id_create_company_id
    "putCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeToObjectIdCreate_to_object_id" = var.connector-oai-hubspotcompanies_property_put_crm_v4_objects_companies_company_id_associations_to_object_type_to_object_id_create_to_object_id
    "putCrmV4ObjectsCompaniesCompanyIdAssociationsToObjectTypeToObjectIdCreate_to_object_type" = var.connector-oai-hubspotcompanies_property_put_crm_v4_objects_companies_company_id_associations_to_object_type_to_object_id_create_to_object_type
  })
}
