resource "pingone_davinci_connector_instance" "iovationConnector" {
  environment_id = var.pingone_environment_id

  connector = {
    id = "iovationConnector"
  }
  name = "My awesome iovationConnector"
  properties = jsonencode({
    "achRoutingNumber" = var.iovationconnector_property_ach_routing_number
    "alternateIp" = var.iovationconnector_property_alternate_ip
    "apiUrl" = var.iovationconnector_property_api_url
    "billingCity" = var.iovationconnector_property_billing_city
    "billingCountry" = var.iovationconnector_property_billing_country
    "billingPostalCode" = var.iovationconnector_property_billing_postal_code
    "billingRegion" = var.iovationconnector_property_billing_region
    "billingShippingMismatch" = var.iovationconnector_property_billing_shipping_mismatch
    "billingStreet" = var.iovationconnector_property_billing_street
    "blackBox" = var.iovationconnector_property_black_box
    "creditCardBin" = var.iovationconnector_property_credit_card_bin
    "email" = var.iovationconnector_property_email
    "emailVerified" = var.iovationconnector_property_email_verified
    "eventId" = var.iovationconnector_property_event_id
    "homePhoneNumber" = var.iovationconnector_property_home_phone_number
    "homePhoneSmsEnabled" = var.iovationconnector_property_home_phone_sms_enabled
    "homePhoneVerified" = var.iovationconnector_property_home_phone_verified
    "integrationPoint" = var.iovationconnector_property_integration_point
    "javascriptCdnUrl" = var.iovationconnector_property_javascript_cdn_url
    "loadingText" = var.iovationconnector_property_loading_text
    "mobilePhoneNumber" = var.iovationconnector_property_mobile_phone_number
    "mobilePhoneSmsEnabled" = var.iovationconnector_property_mobile_phone_sms_enabled
    "mobilePhoneVerified" = var.iovationconnector_property_mobile_phone_verified
    "nextEvent" = var.iovationconnector_property_next_event
    "officePhoneNumber" = var.iovationconnector_property_office_phone_number
    "officePhoneSmsEnabled" = var.iovationconnector_property_office_phone_sms_enabled
    "officePhoneVerified" = var.iovationconnector_property_office_phone_verified
    "onlineId" = var.iovationconnector_property_online_id
    "referrerUrl" = var.iovationconnector_property_referrer_url
    "securityPin" = var.iovationconnector_property_security_pin
    "securityPinType" = var.iovationconnector_property_security_pin_type
    "serviceId" = var.iovationconnector_property_service_id
    "sessionAlias" = var.iovationconnector_property_session_alias
    "shippingCity" = var.iovationconnector_property_shipping_city
    "shippingCountry" = var.iovationconnector_property_shipping_country
    "shippingPostalCode" = var.iovationconnector_property_shipping_postal_code
    "shippingRegion" = var.iovationconnector_property_shipping_region
    "shippingStreet" = var.iovationconnector_property_shipping_street
    "sku" = var.iovationconnector_property_sku
    "subKey" = var.iovationconnector_property_sub_key
    "subscriberAccount" = var.iovationconnector_property_subscriber_account
    "subscriberId" = var.iovationconnector_property_subscriber_id
    "subscriberPasscode" = var.iovationconnector_property_subscriber_passcode
    "tenantId" = var.iovationconnector_property_tenant_id
    "upc" = var.iovationconnector_property_upc
    "userAccountCode" = var.iovationconnector_property_user_account_code
    "userIp" = var.iovationconnector_property_user_ip
    "userReference" = var.iovationconnector_property_user_reference
    "valueAmount" = var.iovationconnector_property_value_amount
    "valueCurrency" = var.iovationconnector_property_value_currency
    "version" = var.iovationconnector_property_version
  })
}
