resource "pingone_davinci_connector_instance" "siftConnector" {
  environment_id = var.pingone_environment_id

  connector = {
    id = "siftConnector"
  }
  name = "My awesome siftConnector"
  properties = jsonencode({
    "abuseTypes" = var.siftconnector_property_abuse_types
    "acceptLanguage" = var.siftconnector_property_accept_language
    "accountId" = var.siftconnector_property_account_id
    "address1Billing" = var.siftconnector_property_address1_billing
    "address1Shipping" = var.siftconnector_property_address1_shipping
    "address2Billing" = var.siftconnector_property_address2_billing
    "address2Shipping" = var.siftconnector_property_address2_shipping
    "analyst" = var.siftconnector_property_analyst
    "apiKey" = var.siftconnector_property_api_key
    "body" = var.siftconnector_property_body
    "changedPassword" = var.siftconnector_property_changed_password
    "cityBilling" = var.siftconnector_property_city_billing
    "cityShipping" = var.siftconnector_property_city_shipping
    "contentLanguage" = var.siftconnector_property_content_language
    "countryBilling" = var.siftconnector_property_country_billing
    "countryShipping" = var.siftconnector_property_country_shipping
    "decisionId" = var.siftconnector_property_decision_id
    "decisionType" = var.siftconnector_property_decision_type
    "description" = var.siftconnector_property_description
    "email" = var.siftconnector_property_email
    "endpoint" = var.siftconnector_property_endpoint
    "failureReason" = var.siftconnector_property_failure_reason
    "fullName" = var.siftconnector_property_full_name
    "fullNameBilling" = var.siftconnector_property_full_name_billing
    "fullNameShipping" = var.siftconnector_property_full_name_shipping
    "headers" = var.siftconnector_property_headers
    "ipAddress" = var.siftconnector_property_ip_address
    "loginStatus" = var.siftconnector_property_login_status
    "method" = var.siftconnector_property_method
    "phoneNumber" = var.siftconnector_property_phone_number
    "phoneNumberBilling" = var.siftconnector_property_phone_number_billing
    "phoneNumberPrimary" = var.siftconnector_property_phone_number_primary
    "phoneNumberShipping" = var.siftconnector_property_phone_number_shipping
    "queryParameters" = var.siftconnector_property_query_parameters
    "reason" = var.siftconnector_property_reason
    "regionBilling" = var.siftconnector_property_region_billing
    "regionShipping" = var.siftconnector_property_region_shipping
    "returnScore" = var.siftconnector_property_return_score
    "scorePercentiles" = var.siftconnector_property_score_percentiles
    "sessionId" = var.siftconnector_property_session_id
    "sessionIdDecision" = var.siftconnector_property_session_id_decision
    "sessionIdOptional" = var.siftconnector_property_session_id_optional
    "source" = var.siftconnector_property_source
    "status" = var.siftconnector_property_status
    "userAgent" = var.siftconnector_property_user_agent
    "userId" = var.siftconnector_property_user_id
    "username" = var.siftconnector_property_username
    "verificationType" = var.siftconnector_property_verification_type
    "verifiedReason" = var.siftconnector_property_verified_reason
    "verifiedValue" = var.siftconnector_property_verified_value
    "workflowStatus" = var.siftconnector_property_workflow_status
    "zipcodeBilling" = var.siftconnector_property_zipcode_billing
    "zipcodeShipping" = var.siftconnector_property_zipcode_shipping
  })
}
