resource "pingone_davinci_connector_instance" "socureConnector" {
  environment_id = var.pingone_environment_id

  connector = {
    id = "socureConnector"
  }
  name = "My awesome socureConnector"
  properties = jsonencode({
    "accountCreationDate" = var.socureconnector_property_account_creation_date
    "apiKey" = var.socureconnector_property_api_key
    "baseUrl" = var.socureconnector_property_base_url
    "bodyData" = var.socureconnector_property_body_data
    "bodyHeaderText" = var.socureconnector_property_body_header_text
    "city" = var.socureconnector_property_city
    "companyName" = var.socureconnector_property_company_name
    "country" = var.socureconnector_property_country
    "customApiUrl" = var.socureconnector_property_custom_api_url
    "customerUserId" = var.socureconnector_property_customer_user_id
    "deviceInterface" = var.socureconnector_property_device_interface
    "deviceSessionId" = var.socureconnector_property_device_session_id
    "deviceType" = var.socureconnector_property_device_type
    "disbursementType" = var.socureconnector_property_disbursement_type
    "dob" = var.socureconnector_property_dob
    "documentUuid" = var.socureconnector_property_document_uuid
    "email" = var.socureconnector_property_email
    "endpoint" = var.socureconnector_property_endpoint
    "firstName" = var.socureconnector_property_first_name
    "geocodes" = var.socureconnector_property_geocodes
    "headers" = var.socureconnector_property_headers
    "lastOrderDate" = var.socureconnector_property_last_order_date
    "method" = var.socureconnector_property_method
    "mobileNumber" = var.socureconnector_property_mobile_number
    "modules" = var.socureconnector_property_modules
    "nationalId" = var.socureconnector_property_national_id
    "operatingSystem" = var.socureconnector_property_operating_system
    "orderAmount" = var.socureconnector_property_order_amount
    "orderChannel" = var.socureconnector_property_order_channel
    "paymentType" = var.socureconnector_property_payment_type
    "phoneNumber" = var.socureconnector_property_phone_number
    "physicalAddress" = var.socureconnector_property_physical_address
    "physicalAddress2" = var.socureconnector_property_physical_address2
    "prevOrderCount" = var.socureconnector_property_prev_order_count
    "queryParams" = var.socureconnector_property_query_params
    "recipientCountry" = var.socureconnector_property_recipient_country
    "screen0Config" = var.socureconnector_property_screen0_config
    "screen1Config" = var.socureconnector_property_screen1_config
    "screen2Config" = var.socureconnector_property_screen2_config
    "sdkKey" = var.socureconnector_property_sdk_key
    "skWebhookUri" = var.socureconnector_property_sk_webhook_uri
    "state" = var.socureconnector_property_state
    "submissionDate" = var.socureconnector_property_submission_date
    "surName" = var.socureconnector_property_sur_name
    "title" = var.socureconnector_property_title
    "verificationCountry" = var.socureconnector_property_verification_country
    "verificationLevel" = var.socureconnector_property_verification_level
    "watchlistFilters" = var.socureconnector_property_watchlist_filters
    "zip" = var.socureconnector_property_zip
  })
}
